/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NorwichRouteImport } from './routes/norwich'
import { Route as HullRouteImport } from './routes/hull'
import { Route as IndexRouteImport } from './routes/index'

const NorwichRoute = NorwichRouteImport.update({
  id: '/norwich',
  path: '/norwich',
  getParentRoute: () => rootRouteImport,
} as any)
const HullRoute = HullRouteImport.update({
  id: '/hull',
  path: '/hull',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hull': typeof HullRoute
  '/norwich': typeof NorwichRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hull': typeof HullRoute
  '/norwich': typeof NorwichRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hull': typeof HullRoute
  '/norwich': typeof NorwichRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hull' | '/norwich'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hull' | '/norwich'
  id: '__root__' | '/' | '/hull' | '/norwich'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HullRoute: typeof HullRoute
  NorwichRoute: typeof NorwichRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/norwich': {
      id: '/norwich'
      path: '/norwich'
      fullPath: '/norwich'
      preLoaderRoute: typeof NorwichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hull': {
      id: '/hull'
      path: '/hull'
      fullPath: '/hull'
      preLoaderRoute: typeof HullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HullRoute: HullRoute,
  NorwichRoute: NorwichRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
