/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatIsPadelRouteImport } from './routes/what-is-padel'
import { Route as PressRouteImport } from './routes/press'
import { Route as NorwichRouteImport } from './routes/norwich'
import { Route as HullRouteImport } from './routes/hull'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as IndexRouteImport } from './routes/index'

const WhatIsPadelRoute = WhatIsPadelRouteImport.update({
  id: '/what-is-padel',
  path: '/what-is-padel',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const NorwichRoute = NorwichRouteImport.update({
  id: '/norwich',
  path: '/norwich',
  getParentRoute: () => rootRouteImport,
} as any)
const HullRoute = HullRouteImport.update({
  id: '/hull',
  path: '/hull',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corporate': typeof CorporateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/hull': typeof HullRoute
  '/norwich': typeof NorwichRoute
  '/press': typeof PressRoute
  '/what-is-padel': typeof WhatIsPadelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corporate': typeof CorporateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/hull': typeof HullRoute
  '/norwich': typeof NorwichRoute
  '/press': typeof PressRoute
  '/what-is-padel': typeof WhatIsPadelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corporate': typeof CorporateRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/hull': typeof HullRoute
  '/norwich': typeof NorwichRoute
  '/press': typeof PressRoute
  '/what-is-padel': typeof WhatIsPadelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corporate'
    | '/events'
    | '/faq'
    | '/hull'
    | '/norwich'
    | '/press'
    | '/what-is-padel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corporate'
    | '/events'
    | '/faq'
    | '/hull'
    | '/norwich'
    | '/press'
    | '/what-is-padel'
  id:
    | '__root__'
    | '/'
    | '/corporate'
    | '/events'
    | '/faq'
    | '/hull'
    | '/norwich'
    | '/press'
    | '/what-is-padel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorporateRoute: typeof CorporateRoute
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  HullRoute: typeof HullRoute
  NorwichRoute: typeof NorwichRoute
  PressRoute: typeof PressRoute
  WhatIsPadelRoute: typeof WhatIsPadelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-is-padel': {
      id: '/what-is-padel'
      path: '/what-is-padel'
      fullPath: '/what-is-padel'
      preLoaderRoute: typeof WhatIsPadelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/norwich': {
      id: '/norwich'
      path: '/norwich'
      fullPath: '/norwich'
      preLoaderRoute: typeof NorwichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hull': {
      id: '/hull'
      path: '/hull'
      fullPath: '/hull'
      preLoaderRoute: typeof HullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorporateRoute: CorporateRoute,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  HullRoute: HullRoute,
  NorwichRoute: NorwichRoute,
  PressRoute: PressRoute,
  WhatIsPadelRoute: WhatIsPadelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
